### ISSUE TITLE
foo_midi chokes on SEM1 chunk

### ISSUE THREAD

**Issue by SamusAranX** [losnoco/foo_midi#1]
MIDI files created by Sony Ericsson phones often have an additional SEM1 chunk right after the MThd chunk. It just contains metadata for use with the MusicDJ app on those phones and removing or skipping it doesn't affect playback. Can you please make it so that foo_midi skips it and plays the MIDI file instead of refusing to open it?

Here's an example MIDI file:
[MusicDJ Demo.zip](https://github.com/losnoco/foo_midi/files/5897880/MusicDJ.Demo.zip)

**Comment by kode54** [comment]
I shall amend my midi processing code to ignore Standard MIDI chunks it doesn't understand, by skipping over them on parsing. I'll do this tonight.

**Comment by kode54** [comment]
This is now fixed.
